name: Docker Image CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.x'
        
    - name: Build the Docker image
      working-directory: path
      run: docker build .
